development:
  adapter: postgresql
  database: raia8_desenv
  host: localhost
  username: postgres
  password: 123456

test:
  adapter: postgresql
  database: raia8_test
  host: localhost
  username: postgres
  password: 123456

production:
  adapter: postgresql
  database: raia8_production
  host: localhost
  username: raia8
  password: raia8
